contact_links:
  - name: 💬 General Support
    url: https://github.com/xdev-software/jcon-scheduler?tab=readme-ov-file#general-support
    about: "If you have other general problems that are not related to the Scheduler/schedule app"
