contact_links:
  - name: 💬 General Support - On site
    url: https://schedule.jcon.one/help
    about: "If you other general problems like lost tickets or don't know where the coffee can be found"
  - name: 💬 General Support - Mail
    url: "mailto:info@jcon.one"
    about: "If you other general problems like lost tickets or don't know where the coffee can be found"
